### ISSUE TITLE
BiographySampo: add idm:Provided_Person instances

### ISSUE THREAD

**Issue by yoge1** [InTaVia/source-dataset-conversion#11]
E.g. for https://www.intavia.org/personproxy/bs/10, add the following triples:

<https://www.intavia.org/personproxy/bs/10> idm:person_proxy_for <https://www.intavia.org/provided_person/bs/10> .
<https://www.intavia.org/provided_person/bs/10> a idm:Provided_Person .

**Comment by ptleskin** [comment]
Added to the data transformation process.
