### ISSUE TITLE
APIS: add crm:P98_brought_into_life and crm:P100_was_death_of predicates to births and deaths events 

### ISSUE THREAD

**Issue by yoge1** [InTaVia/source-dataset-conversion#16]
The predicates crm:P98_brought_into_life and crm:P100_was_death_of are used in BiographySampo and BiographyNet, but I at least I didn't manage to see see them in APIS.

**Comment by sennierer** [comment]
yes, saw that too. carla used proxy -> idmcore:inheres_in -> roletype <- had_participant_in_role - E67_Birth . I am not sure if this is 100% compliant with crm, but as far as I see it that model would allow us to treat birth and death just as another event with a eventtype, a role of the person start and end dates and possibly a place. That would allow us to stick with very close to what the IDM json looks like at the moment and have a simple sparql query.
That said, we can of course additionally add the crm triples, but I would suggest to maybe also add the other triples in your datasets. I added a first history endpoint version to grlc: https://grlc.acdh-dev.oeaw.ac.at/api/InTaVia/grlc_sparql#/default/get_person_history_json use eg http://www.intavia.eu/person/9965 as an input for the query to see the birth events.

**Comment by CarlaVS** [comment]
I also included the crm:P98_brought_into_life and crm:P100_was_death_of model now
