### ISSUE TITLE
[BiographySampo] P81a_begin_of_the_begin instead of P82a_begin_of_the_begin

### ISSUE THREAD

**Issue by sennierer** [InTaVia/source-dataset-conversion#23]
The serialization of BiographySampo uses P81a_begin_of_the_begin instead of P82a_begin_of_the_begin. See https://cidoc-crm.org/rdfs/7.1.1/CIDOC_CRM_v7.1.1.rdfs

**Comment by sennierer** [comment]
and the serialization is using a wrong dateTime format: YYYY-MM-DD+HH:MM:SS is used by BS. Whereas it should be YYYY-MM-DDTHH:MM:SSZ . this is needed to allow for before and after queries in the sparql endpoint. currently thats not working

**Comment by sennierer** [comment]
So essentially the plus sign as delimiter between day and time needs to be changed to a T and a Z as a delimiter for the timezone (which can be omitted) needs to be added at the end.

**Comment by ptleskin** [comment]
The data converted from BS already uses the datetimes in format "YYYY-MM-DDTHH:MM:SS"?

The format "YYYY-MM-DD+HH:MM:SS" is used in the current version of SBI_dataset/sbi.ttl

**Comment by joahim** [comment]
Correct, thanks for pointing this out @ptleskin. I have now fixed it and republished the data.

**Comment by sennierer** [comment]
ok, sorry that I mixed up datasets and thanks for clarifying @ptleskin and thanks for fixing this so fast @joahim . @ptleskin  could you please nonetheless fix the P81a issue? Its not super urgent, I changed the queries to use the end_of_the_end instead, but would be good to have it fixed nonetheless.

**Comment by ptleskin** [comment]
'P82a_begin_of_the_begin' now used in BS

**Comment by sennierer** [comment]
great, thx. Just uploaded your new data to the triplestore
