### ISSUE TITLE
inconsistencies in spaceprimitive

### ISSUE THREAD

**Issue by sennierer** [InTaVia/source-dataset-conversion#24]
APIS uses `Point ( xx )`
whereas BS uses `POINT xx`

**Comment by ptleskin** [comment]
BS data is now updated using the format "Point ( +x +y )"^^geo:wktLiteral

**Comment by sennierer** [comment]
Hi, can you please have another look at the BS geo serialization. Looks like now its `Point ( LON LAT )` whereas it should be the other way around: `Point ( LAT LON )`.

**Comment by ptleskin** [comment]
Is it? There's this comment regarding the coordinate format by Carla that states the order to be `"POINT Longitude Latitude"` https://github.com/InTaVia/source-dataset-conversion/issues/2#issuecomment-1211649839

as well as this documentation https://www.w3.org/2015/spatial/wiki/Coordinate_Reference_Systems#GeoSPARQL  `WGS84 with the order longitude, latitude`

and I checked that the latitude of Helsinki, Finland is 60.1..., and the longitude is 24.9... and we have `"Point ( +24.9384 +60.1699 )"^^geo:wktLiteral`

**Comment by sennierer** [comment]
:) you are right, sorry for the hassle, should read [my on comments](https://github.com/InTaVia/source-dataset-conversion/issues/2#issuecomment-1180250876) more carefully ;). will fix it in our serialization

**Comment by sennierer** [comment]
added a new issue for the APIS serialization (#28)
