### ISSUE TITLE
[BS] two (or more?) timespans per event?

### ISSUE THREAD

**Issue by sennierer** [InTaVia/source-dataset-conversion#31]
this [event](https://mp-playground.acdh-dev.oeaw.ac.at/resource/?uri=http://www.intavia.eu/bs/event/6010-31) has two timespans, both with P82a_begin_of_the_begin and P82b_end_of_the_end set. One has the label 1933 and the other 1937. Is that by intention or should it rather be one timespan with P82a_begin_of_the_begin set to 1933-01-01 and P81a_end_of_the_begin set to 1933-12-31, P82b_end_of_the_end set to 1937-12-31 and P81b_begin_of_the_end set to 1937-01-01. Label should then be 1933 -1937.

This currently breaks the API.

**Comment by yoge1** [comment]
If possible, split the event into multiple events (one event per timespan). When not possible, change modeling from using multiple timespans to one timespan covering all the individual ones.

**Comment by ptleskin** [comment]
BS data updated, now without cases of multiple time_spans.
