### ISSUE TITLE
[BNet] is BiographyNET using bio-crm event predicates?

### ISSUE THREAD

**Issue by sennierer** [InTaVia/source-dataset-conversion#32]
it seems like that BNet is not using the agreed modelling of events `crm:E21_person -> bio-crm:bearer_of -> bio-crm:Event_Role <-  bio-crm:had_participant_in_role <- crm:E5_Event`, but rather `crm:E21_Person <- crm:P21_had_participant`. Is this the case for all the events, or only those that you dont know the role of the person? And can we switch to include the bio-crm path to simplify querying in the API?

**Comment by biktorrr** [comment]
Hi Matthias,

I think this is not the case. In Bionet we actually do both: so both an event and an Event_role are created. I do use mostly subproperties of bearer_of (has_occupation and others), maybe that is it?

For example

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX wdr: <http://www.w3.org/2007/05/powder#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX bioc: <http://ldf.fi/schema/bioc/>
SELECT * WHERE {
  <http://data.biographynet.nl/rdf/PersonDes-1000108_02> bioc:has_occupation ?occ .
  ?role bioc:had_participant_in_role ?occ.
  ?evt crm:P11_had_participant <http://data.biographynet.nl/rdf/PersonDes-1000108_02>
}

Gives the occupation role (shared with many others that have that role, and the person-specific event

best
Victor
________________________________
From: Matthias Schlögl ***@***.***>
Sent: Friday, October 14, 2022 09:27
To: InTaVia/source-dataset-conversion ***@***.***>
Cc: Boer, V. de (Victor) ***@***.***>; Assign ***@***.***>
Subject: [InTaVia/source-dataset-conversion] [BNet] is BiographyNET using bio-crm event predicates? (Issue #32)


it seems like that BNet is not using the agreed modelling of events crm:E21_person -> bio-crm:bearer_of -> bio-crm:Event_Role <- bio-crm:had_participant_in_role <- crm:E5_Event, but rather crm:E21_Person <- crm:P21_had_participant. Is this the case for all the events, or only those that you dont know the role of the person? And can we switch to include the bio-crm path to simplify querying in the API?

**Comment by sennierer** [comment]
oh, yes, sorry missed that. bio-crm relations are there. Closing the issue.
