### ISSUE TITLE
inconsistent modelling of gender

### ISSUE THREAD

**Issue by sennierer** [InTaVia/source-dataset-conversion#37]
BS has `pers bioc:gender gender`
whereas biographynet uses `pers biox:has_gender gender`
in APIS data gender got missing

**Comment by biktorrr** [comment]
I guess the has_gender one is correct, no? https://github.com/InTaVia/idm-rdf/blob/main/idm-OWL/intavia_idm1.owl

**Comment by sennierer** [comment]
you are right according to http://150.146.207.114/lode/extract?owlapi=true&url=http://ldf.fi/schema/bioc/#d4e54 `bioc:has_gender` is correct.
@yoge1 and @ptleskin can you fix that in BS?

**Comment by ptleskin** [comment]
BS data now updated to use bioc:has_gender
