### ISSUE TITLE
Harmonize IDM URI usage (http vs https)

### ISSUE THREAD

**Issue by biktorrr** [InTaVia/source-dataset-conversion#4]
The biographynet conversion uses http while others use https URIs for IDM. We should use the one in the IDM OWL ontology.

**Comment by biktorrr** [comment]
as input: https://www.w3.org/blog/2016/05/https-and-the-semantic-weblinked-data/

**Comment by yoge1** [comment]
A comment on the page Victor linked: "An identifier should not have to worry about secure or insecure resolution. The infrastructure should take care of that in the background, which I understand HSTS and UIR are designed to do.", but I don't have strong objection on using https, either.

**Comment by biktorrr** [comment]
We stick with http (since most other namespaces also do that)
