### ISSUE TITLE
[BS] `bioc:Person_Relationship_Role` missing

### ISSUE THREAD

**Issue by sennierer** [InTaVia/source-dataset-conversion#44]
Moved the new new BS file to the data-source repo, created a PR and the automatic shacl validation shows that the new ttl is missing the `bioc:Person_Relationship_Role` class for the roles. Can you have a look at the [report](https://github.com/InTaVia/source-data/pull/2/checks), see if that makes sense and change accordingly if it does? Btw.: improvements to the [shacl constraints](https://github.com/InTaVia/source-data/blob/main/IKG_shacl_shapes.ttl) are obviously very welcome.

**Comment by sennierer** [comment]
hmm...to fulfill the shacl validation I added `APIS_role rdfs:subClassOf bioc:Person_Relationship_Role` triple. But you are obviously right, we should have a common class that we inherit from.

**Comment by sennierer** [comment]
And I see we already created something like that here https://github.com/InTaVia/idm-rdf/blob/main/idm-OWL/intavia_idm_classes_1.ttl ;)
Should we add the triples there?

**Comment by yoge1** [comment]
Yes, I think that https://github.com/InTaVia/idm-rdf/blob/main/idm-OWL/intavia_idm_classes_1.ttl would be good for adding the role classes.

**Comment by yoge1** [comment]
@ptleskin will add the role class definitions in the file https://github.com/InTaVia/idm-rdf/blob/main/idm-OWL/intavia_idm_classes_1.ttl with a SPARQL CONSTRUCT based on used classes in IKG.

**Comment by ptleskin** [comment]
Updated https://github.com/InTaVia/idm-rdf/blob/main/idm-OWL/intavia_idm_classes_1.ttl
